<?php

/*
|--------------------------------------------------------------------------
| Daily Report (Z-Report & Employee Summary)
|--------------------------------------------------------------------------
|
| Strings for the printable daily report and the Reports tab that generates it.
| Kept in its own file so the report can be re-themed or re-worded without
| touching the much larger dashboard.php.
|
*/

return [

    // ── Reports tab (filter screen) ──────────────────────────────────────
    'tab'                => 'Reports',
    'tab_title'          => 'Daily Report',
    'tab_subtitle'       => 'Z-Report & employee summary for a single day or a date range.',

    'mode'               => 'Period',
    'mode_day'           => 'Single day',
    'mode_range'         => 'Date range',
    'date'               => 'Date',
    'from'               => 'From',
    'to'                 => 'To',
    'quick_ranges'       => 'Quick select',
    'today'              => 'Today',
    'yesterday'          => 'Yesterday',
    'this_week'          => 'This week',
    'this_month'         => 'This month',
    'last_month'         => 'Last month',

    'employees'          => 'Employees',
    'all_employees'      => 'All employees',
    'employees_selected' => ':count selected',
    'select_all'         => 'Select all',
    'clear'              => 'Clear',

    'generate'           => 'Generate report',
    'generate_hint'      => 'Opens the printable report in a new tab.',
    'invalid_range'      => 'The start date must be on or before the end date.',
    'range_too_long'     => 'The range may not exceed :days days.',

    'preview_title'      => 'Preview',
    'preview_hint'       => 'Live totals for the selected period.',

    // ── Report document ──────────────────────────────────────────────────
    'title'              => 'Daily Report',
    'subtitle'           => 'Z-Report & Employee Summary',
    'range_label'        => 'Period',
    'date_label'         => 'Date',
    'printed'            => 'Printed',
    'generated_by'       => 'Generated by',
    'print'              => 'Print',
    'close'              => 'Close',

    'filtered_notice'    => 'Filtered report — covers selected employees only, not the whole salon.',

    // Sales
    'sales_title'        => 'Sales Summary',
    'method'             => 'Payment method',
    'transactions'       => 'Transactions',
    'amount'             => 'Amount',
    'cash'               => 'Cash',
    'card'               => 'Card',
    'online'             => 'Online',
    'total_sales'        => 'Total sales',

    // Payment split
    'payment_title'      => 'Payment Summary',

    // Totals
    'totals_title'       => 'Report Totals',
    'total_transactions' => 'Total transactions',
    'total_receipts'     => 'Numbered receipts',
    'total_customers'    => 'Total customers',
    'total_services'     => 'Services sold',
    'avg_ticket'         => 'Average ticket',

    // VAT
    'vat_title'          => 'VAT Summary',
    'vat_rate'           => 'Rate',
    'vat_net'            => 'Net',
    'vat_tax'            => 'VAT',
    'vat_gross'          => 'Gross',
    'vat_note'           => 'Prices are gross; VAT is extracted by reverse calculation.',

    // Discounts
    'discount_title'     => 'Discounts',
    'discount_total'     => 'Total discounts granted',
    'discount_count'     => 'Discounted receipts',
    'discount_before'    => 'Total before discount',
    'discount_percent'   => 'Share of gross',

    // Operations
    'operations_title'   => 'Operations',
    'source_title'       => 'Booking source',
    'source_app'         => 'App / Online',
    'source_reception'   => 'Reception',
    'cancelled'          => 'Cancelled',
    'no_show'            => 'No-show',
    'outstanding'        => 'Outstanding',
    'outstanding_count'  => 'Unpaid bookings',
    'scheduled_note'     => 'Counted by appointment date — unpaid bookings have no collection date.',

    // Services
    'services_title'     => 'Services Breakdown',
    'service'            => 'Service',
    'qty'                => 'Qty',
    'revenue'            => 'Revenue',
    'share'              => 'Share',
    'services_empty'     => 'No services were delivered in this period.',

    // Employees
    'employee_summary'   => 'Employee Summary',
    'employee_details'   => 'Employee Details',
    'employee'           => 'Employee',
    'appointments'       => 'Appointments',
    'services'           => 'Services',
    'cash_sales'         => 'Cash sales',
    'card_sales'         => 'Card sales',
    'online_sales'       => 'Online sales',
    'total_revenue'      => 'Total revenue',
    'customers'          => 'Customers',
    'working_time'       => 'Working time',
    'worked'             => 'Time worked',
    'top_service'        => 'Top service',
    'sessions'           => ':count sessions',
    'still_clocked_in'   => 'still clocked in',
    'no_attendance'      => 'Not clocked in',
    'total_row'          => 'TOTAL',
    'employees_empty'    => 'No employees to show.',

    // Daily breakdown
    'daily_title'        => 'Daily Performance',
    'day'                => 'Date',

    // Transaction appendix
    'appendix_title'     => 'Transactions',
    'invoice_no'         => 'Invoice',
    'time'               => 'Time',
    'customer'           => 'Customer',
    'provider'           => 'Employee',
    'appendix_empty'     => 'No transactions were collected in this period.',

    // Footer
    'report_id'          => 'Report ID',
    'footer_note'        => 'Generated from booking and invoice records. Figures are based on the date payment was collected.',
    'empty_report'       => 'No money was collected in this period.',
];
